// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: inference/inference/inference_revalidations.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RevalidationVote is a single participant's vote in a revalidation round.
type RevalidationVote struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Weight  int64  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Pass    bool   `protobuf:"varint,3,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (m *RevalidationVote) Reset()         { *m = RevalidationVote{} }
func (m *RevalidationVote) String() string { return proto.CompactTextString(m) }
func (*RevalidationVote) ProtoMessage()    {}
func (*RevalidationVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7c29efef5027b50, []int{0}
}
func (m *RevalidationVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RevalidationVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RevalidationVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RevalidationVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevalidationVote.Merge(m, src)
}
func (m *RevalidationVote) XXX_Size() int {
	return m.Size()
}
func (m *RevalidationVote) XXX_DiscardUnknown() {
	xxx_messageInfo_RevalidationVote.DiscardUnknown(m)
}

var xxx_messageInfo_RevalidationVote proto.InternalMessageInfo

func (m *RevalidationVote) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RevalidationVote) GetWeight() int64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *RevalidationVote) GetPass() bool {
	if m != nil {
		return m.Pass
	}
	return false
}

// InferenceRevalidations holds all revalidation votes for one inference (key = inference_id).
type InferenceRevalidations struct {
	Votes []*RevalidationVote `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
}

func (m *InferenceRevalidations) Reset()         { *m = InferenceRevalidations{} }
func (m *InferenceRevalidations) String() string { return proto.CompactTextString(m) }
func (*InferenceRevalidations) ProtoMessage()    {}
func (*InferenceRevalidations) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7c29efef5027b50, []int{1}
}
func (m *InferenceRevalidations) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InferenceRevalidations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InferenceRevalidations.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InferenceRevalidations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InferenceRevalidations.Merge(m, src)
}
func (m *InferenceRevalidations) XXX_Size() int {
	return m.Size()
}
func (m *InferenceRevalidations) XXX_DiscardUnknown() {
	xxx_messageInfo_InferenceRevalidations.DiscardUnknown(m)
}

var xxx_messageInfo_InferenceRevalidations proto.InternalMessageInfo

func (m *InferenceRevalidations) GetVotes() []*RevalidationVote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func init() {
	proto.RegisterType((*RevalidationVote)(nil), "inference.inference.RevalidationVote")
	proto.RegisterType((*InferenceRevalidations)(nil), "inference.inference.InferenceRevalidations")
}

func init() {
	proto.RegisterFile("inference/inference/inference_revalidations.proto", fileDescriptor_d7c29efef5027b50)
}

var fileDescriptor_d7c29efef5027b50 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0xcc, 0xcc, 0x4b, 0x4b,
	0x2d, 0x4a, 0xcd, 0x4b, 0x4e, 0xd5, 0xc7, 0xc2, 0x8a, 0x2f, 0x4a, 0x2d, 0x4b, 0xcc, 0xc9, 0x4c,
	0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x86, 0x4b,
	0xeb, 0xc1, 0x59, 0x4a, 0x11, 0x5c, 0x02, 0x41, 0x48, 0x6a, 0xc3, 0xf2, 0x4b, 0x52, 0x85, 0x24,
	0xb8, 0xd8, 0x13, 0x53, 0x52, 0x8a, 0x52, 0x8b, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x60, 0x5c, 0x21, 0x31, 0x2e, 0xb6, 0xf2, 0xd4, 0xcc, 0xf4, 0x8c, 0x12, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xe6, 0x20, 0x28, 0x4f, 0x48, 0x88, 0x8b, 0xa5, 0x20, 0xb1, 0xb8, 0x58, 0x82, 0x59, 0x81,
	0x51, 0x83, 0x23, 0x08, 0xcc, 0x56, 0x0a, 0xe5, 0x12, 0xf3, 0x84, 0x59, 0x83, 0x6c, 0x45, 0xb1,
	0x90, 0x35, 0x17, 0x6b, 0x59, 0x7e, 0x49, 0x2a, 0xc8, 0x74, 0x66, 0x0d, 0x6e, 0x23, 0x55, 0x3d,
	0x2c, 0x0e, 0xd3, 0x43, 0x77, 0x55, 0x10, 0x44, 0x8f, 0x93, 0xff, 0x89, 0x47, 0x72, 0x8c, 0x17,
	0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c,
	0x37, 0x1e, 0xcb, 0x31, 0x44, 0x99, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7,
	0xea, 0x17, 0x14, 0xe5, 0xa7, 0x94, 0x26, 0x97, 0x14, 0x27, 0x67, 0xa2, 0x05, 0x51, 0x05, 0x12,
	0xbb, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0x1c, 0x3a, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0xc8, 0xc6, 0xb0, 0x52, 0x01, 0x00, 0x00,
}

func (m *RevalidationVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RevalidationVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RevalidationVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pass {
		i--
		if m.Pass {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Weight != 0 {
		i = encodeVarintInferenceRevalidations(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintInferenceRevalidations(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InferenceRevalidations) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InferenceRevalidations) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InferenceRevalidations) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Votes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintInferenceRevalidations(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintInferenceRevalidations(dAtA []byte, offset int, v uint64) int {
	offset -= sovInferenceRevalidations(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RevalidationVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovInferenceRevalidations(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovInferenceRevalidations(uint64(m.Weight))
	}
	if m.Pass {
		n += 2
	}
	return n
}

func (m *InferenceRevalidations) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Votes) > 0 {
		for _, e := range m.Votes {
			l = e.Size()
			n += 1 + l + sovInferenceRevalidations(uint64(l))
		}
	}
	return n
}

func sovInferenceRevalidations(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozInferenceRevalidations(x uint64) (n int) {
	return sovInferenceRevalidations(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RevalidationVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInferenceRevalidations
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RevalidationVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RevalidationVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInferenceRevalidations
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInferenceRevalidations
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInferenceRevalidations
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInferenceRevalidations
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pass", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInferenceRevalidations
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pass = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipInferenceRevalidations(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInferenceRevalidations
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InferenceRevalidations) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInferenceRevalidations
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InferenceRevalidations: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InferenceRevalidations: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInferenceRevalidations
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInferenceRevalidations
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInferenceRevalidations
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, &RevalidationVote{})
			if err := m.Votes[len(m.Votes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInferenceRevalidations(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthInferenceRevalidations
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInferenceRevalidations(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInferenceRevalidations
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInferenceRevalidations
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInferenceRevalidations
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInferenceRevalidations
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupInferenceRevalidations
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthInferenceRevalidations
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthInferenceRevalidations        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInferenceRevalidations          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupInferenceRevalidations = fmt.Errorf("proto: unexpected end of group")
)
